---

# Paths

main_path: "/media/ulgen/Samsung/contradiction_data/"
nli_set_train: "/media/ulgen/Samsung/contradiction_data/nli_sets/train.jsonl"
nli_set_dev: "/media/ulgen/Samsung/contradiction_data/nli_sets/dev.jsonl"
nli_set_test: "/media/ulgen/Samsung/contradiction_data/nli_sets/test.jsonl"
processed_nli: "/media/ulgen/Samsung/contradiction_data/processed_nli/"
results: "/media/ulgen/Samsung/contradiction_data/results/"


# Trained model paths

model_paths:
  esim: "/media/ulgen/Samsung/contradiction_data/nli_models/esim/"
  decomposable_attention: "/media/ulgen/Samsung/contradiction_data/nli_models/decomposable_attention/"

# Transformers Paths

transformer_paths:
  bert: "/media/ulgen/Samsung/contradiction_data/transformers/bert/"
  fasttext: "/media/ulgen/Samsung/contradiction_data/transformers/fasttext/"
  word2vec: "/media/ulgen/Samsung/contradiction_data/transformers/word2vec/"
  glove: "/media/ulgen/Samsung/contradiction_data/transformers/glove/"
  tf_hub_path: "/media/ulgen/Samsung/contradiction_data/transformers/tf_hub"

# Network Parameters

nr_unk: 100
max_length: 64
nr_hidden: 512
dropout: 0.2
learn_rate: 0.0001
batch_size: 32
nr_epoch: 3
nr_class: 3
early_stopping: 1